import json,os,subprocess,time
from pathlib import Path
from gear_sonic.research.hindsight_training.runtime import sha
p=Path(__file__).resolve().parent;repo=Path.cwd();prior=p.parent/'m2s-nav-supported-recovery-20260913';checkpoint=prior/'dagger-fit/training/step-003000.pt'
cases=[dict(task='00976-stop-clear',seed=91261,switch=191),dict(task='00265-stop-clear',seed=91261,switch=187),dict(task='00908-stop-corridor',seed=91261,switch=230),dict(task='00908-stop-clear',seed=91260,switch=280)]
providers=[dict(kind=kind,position_gain=.8,velocity_gain=.5,max_speed_mps=.35,max_shift_m=.2,activation_radius_m=.6) for kind in ['nominal','goal_velocity','goal_velocity_keypoints']]
plan=dict(purpose='Test executed goal-regulating command continuations at current adapter failure states',behavior_checkpoint=dict(path=str(checkpoint),sha256=sha(checkpoint)),cases=cases,providers=providers,max_probes=12,selection='greatest timely supported case count, ties favor nominal then velocity then velocity_keypoints',followup='eight early takeovers on seed 91261 using selected provider; retain failed attempts',training='two equal 3000-update forks from the same current adapter: existing replay versus 50% newly qualified recovery plus existing replay; same training seed 91470, architecture, objective and normalization',evaluation='all eight original train tasks at seed 91260 for both forks, then selected fork on all eight seed 91262; ties favor replay. No intermediate checkpoint selection.',held_out_evaluation_seed=91262,observation_contract='no time-to-deadline input; nominal reference remains privileged training only',local_support='report stabilization separately from original-deadline success; no late rows enter timely training view')
(p/'plan.json').write_text(json.dumps(plan,indent=2));rows=json.loads((p/"probe-results.json").read_text())
for case in cases:
 task=case['task'];prefix='confirm-' if case['seed']==91261 else 'dagger-';source=prefix+task
 for provider in providers:
  if any(r["case"] == case and r["provider"] == provider for r in rows):continue
  name=f"probe-{case['seed']}-{task}-{provider['kind']}";name=name+"-retry1" if (p/name).exists() else name;out=p/name;out.mkdir();c=json.loads((prior/(source+'-config.json')).read_text());c.update(output=str(out/'task'),takeover_tick=case['switch'],motor_checkpoint='/home/linjiw/research-data/m2s-bfm-motor-recovery-20260913/scale/training/step-003200.pt',motor_sha256='1e1ed0efaf386245afc59fda3f0e7fd1ee13ba23b3ad3c4cfd6fe0892c8b94cf',continuation=provider);cp=p/(name+'-config.json');cp.write_text(json.dumps(c,indent=2));cmd=json.loads((prior/source/'command.json').read_text());rep={'++eval_output_dir':str(out/'unused'),'++eval_base_dir':str(out/'hydra'),'++callbacks.im_eval.stage_config':str(cp),'++callbacks.im_eval._target_':'gear_sonic.research.scene_distillation.navigation_recovery.MotorRecoveryCollectionCallback'};cmd=[a.split('=',1)[0]+'='+rep[a.split('=',1)[0]] if a.split('=',1)[0] in rep else a for a in cmd];(out/'command.json').write_text(json.dumps(cmd,indent=2));(out/'source-sha256.json').write_text(json.dumps({str(f):sha(f) for f in (repo/'gear_sonic/research/scene_distillation').glob('*.py')},indent=2));t=time.monotonic()
  with (out/'process.log').open('w') as f:r=subprocess.run(cmd,env=dict(os.environ,PYTHONPATH=str(repo),OMP_NUM_THREADS='2',MKL_NUM_THREADS='2'),stdout=f,stderr=subprocess.STDOUT,timeout=360)
  if r.returncode:raise RuntimeError(name)
  receipt=json.loads((out/'task/recovery.json').read_text());row=dict(stage=name,case=case,provider=provider,wall_seconds=time.monotonic()-t,supported=receipt['supported'],supported_rows=receipt['supported_rows'],outcomes=receipt['continuation_outcomes']);rows.append(row);(p/'probe-results.json').write_text(json.dumps(rows,indent=2));print(name,row['supported'],row['outcomes']['local_score']['max_hold_ticks'],round(row['wall_seconds'],1),flush=True)
print('COMPLETE',flush=True)
