import json,os,subprocess,time
from pathlib import Path
import numpy as np
from gear_sonic.research.hindsight_training.runtime import sha
p=Path(__file__).resolve().parent;repo=Path.cwd();old=p.parent/'m2s-nav-motor-bridge-20260913';cbase=json.loads((old/'fit-config.json').read_text())
plan=dict(scope='eight original training tasks, unchanged deadlines; fixed motor',motor_demonstrations=8,offline_updates=6000,dagger_rounds=1,recovery_attempts=8,recovery_switch_rule='half the original teacher first-success tick, floor',dagger_updates=3000,replay_control_updates=3000,batch_size=256,training_seed=91370,evaluation_seed=91260,qualification='full executed post-switch hold and contact-free whole attempt',admitted_rows='executed successful motor suffix only; prefix targets excluded',sources=['exact_motor_demonstrations','fresh_navigation_prefix_recoveries'])
(p/'plan.json').write_text(json.dumps(plan,indent=2));parents=[];results=[]
for cp in sorted(old.glob('full-*-config.json')):
 task=cp.stem.removeprefix('full-').removesuffix('-config');name='motor-'+task;out=p/name;out.mkdir();c=json.loads(cp.read_text());c.update(motor_checkpoint=cbase['motor_checkpoint'],motor_sha256=cbase['motor_sha256'],takeover_tick=0,output=str(out/'task'));path=p/(name+'-config.json');path.write_text(json.dumps(c,indent=2));cmd=json.loads((old/('full-'+task)/'command.json').read_text());rep={'++eval_output_dir':str(out/'unused'),'++eval_base_dir':str(out/'hydra'),'++callbacks.im_eval.stage_config':str(path),'++callbacks.im_eval._target_':'gear_sonic.research.scene_distillation.navigation_recovery.MotorRecoveryCollectionCallback'};cmd=[a.split('=',1)[0]+'='+rep[a.split('=',1)[0]] if a.split('=',1)[0] in rep else a for a in cmd];(out/'command.json').write_text(json.dumps(cmd,indent=2));(out/'source-sha256.json').write_text(json.dumps({str(f):sha(f) for f in (repo/'gear_sonic/research/scene_distillation').glob('*.py')},indent=2));t=time.monotonic()
 with (out/'process.log').open('w') as f:r=subprocess.run(cmd,env=dict(os.environ,PYTHONPATH=str(repo),OMP_NUM_THREADS='2',MKL_NUM_THREADS='2'),stdout=f,stderr=subprocess.STDOUT,timeout=300)
 if r.returncode:raise RuntimeError((name,r.returncode))
 receipt=out/'task/recovery.json';r=json.loads(receipt.read_text());z=np.load(out/'task/trace.npz');b=np.load(old/('full-'+task)/'task/trace.npz');same=all(np.array_equal(z[k],b[k]) for k in ('root_xyz','speed','undesired_force'));assert same,(name,'changed physical trajectory');print(name,r['supported'],r['rows'],same,round(time.monotonic()-t,1),flush=True);parents.append(dict(path=str(receipt),sha256=sha(receipt)));results.append(dict(task=task,supported=r['supported'],rows=r['rows'],exact_archived_motor_trace=same))
(p/'motor-manifest.json').write_text(json.dumps(dict(schema='motor_navigation_recovery_manifest_v1',parents=parents),indent=2));(p/'motor-results.json').write_text(json.dumps(results,indent=2));print('COMPLETE',flush=True)
