import json,os,subprocess,time
from pathlib import Path
from gear_sonic.research.hindsight_training.runtime import sha
p=Path(__file__).resolve().parent;repo=Path.cwd();plan=json.loads((p/'confirmation-plan.json').read_text());candidates=['motor-data','replay-control','dagger'];available=[s for s in candidates if (p/(s+'-results.json')).exists()];chosen=max(available,key=lambda s:sum(r['navigation_success'] for r in json.loads((p/(s+'-results.json')).read_text())));(p/'selected-for-confirmation.json').write_text(json.dumps(dict(condition=chosen,selection_rule=plan['selection'],main_successes=sum(r['navigation_success'] for r in json.loads((p/(chosen+'-results.json')).read_text()))),indent=2));rows=[]
for entry in json.loads((p/(chosen+'-results.json')).read_text()):
 source=entry['stage'];task=source.removeprefix(chosen+'-');name='confirm-'+task;out=p/name;out.mkdir();c=json.loads((p/(source+'-config.json')).read_text());c['output']=str(out/'task');cp=p/(name+'-config.json');cp.write_text(json.dumps(c,indent=2));cmd=json.loads((p/source/'command.json').read_text());rep={'++seed':str(plan['evaluation_seed']),'++eval_output_dir':str(out/'unused'),'++eval_base_dir':str(out/'hydra'),'++callbacks.im_eval.stage_config':str(cp)};cmd=[a.split('=',1)[0]+'='+rep[a.split('=',1)[0]] if a.split('=',1)[0] in rep else a for a in cmd];(out/'command.json').write_text(json.dumps(cmd,indent=2));(out/'source-sha256.json').write_text(json.dumps({str(f):sha(f) for f in (repo/'gear_sonic/research/scene_distillation').glob('*.py')},indent=2));t=time.monotonic()
 with (out/'process.log').open('w') as f:r=subprocess.run(cmd,env=dict(os.environ,PYTHONPATH=str(repo),OMP_NUM_THREADS='2',MKL_NUM_THREADS='2'),stdout=f,stderr=subprocess.STDOUT,timeout=300)
 if r.returncode:raise RuntimeError(name)
 score=json.loads((out/'task/task-result.json').read_text());rows.append(dict(stage=name,**score));print(name,score['navigation_success'],score['max_hold_ticks'],round(time.monotonic()-t,1),flush=True)
(p/'confirmation-results.json').write_text(json.dumps(dict(condition=chosen,seed=plan['evaluation_seed'],evaluations=rows,successes=sum(r['navigation_success'] for r in rows)),indent=2));print('COMPLETE',flush=True)
