#!/usr/bin/env bash
# Exact command executed from the repository root; refuses to overwrite its report.
# To reproduce, change only the output report path to a fresh path before running.
set -euo pipefail
.venv_isaaclab/bin/python - <<'PY'
from pathlib import Path
import json,hashlib,sys,datetime
sys.path[:0]=[str(Path.cwd()),str(Path.cwd()/'scripts/research')]
import motion2scene_build_timed_replay as replay
D=Path('/home/linjiw/research-data/groot-wbc');o=D/'m2s-expanded-and-capability-stages-20260910-v8';root=D/'m2s-expanded-acquisition-20260909-v1/seed93202_target_only';tick=70

def ref(p):return {'path':str(p.absolute()),'sha256':'sha256:'+hashlib.sha256(p.read_bytes()).hexdigest()}
cp=ref(root/'controller/complete_007.json');c=replay.read_bound(cp);training=replay.read_bound(c['training_result']);reg=replay.read_bound(training['registration']);groups=replay.read_bound(training['teachers']);group=groups[-1];teacher=replay.read_bound(group['collection']);tm=replay.read_bound(teacher['manifest'])
pre_ref=ref(root/'round_007/preupdate.json');pre=replay.read_bound(pre_ref);old_training=replay.read_bound(pre['training_result']);assert groups[:-1]==replay.read_bound(old_training['teachers']);assert reg['l2']==10.0 and reg['weighting']=='uniform_per_phase'
sr_ref=ref(root/'round_007/student/result.json');student=replay.read_bound(sr_ref);sm=replay.read_bound(student['manifest']);assert sm['policy']==pre['model']==old_training['policy'];assert ref(Path(sm['policy']['path']))==sm['policy'];assert sm['registry']==tm['registry'] and sm['scene_definition']==tm['scene_definition'];assert sm['cells'][0]['runtime_seed']==group['physics_seed']==93202
s=student['rows'][0];t=next(r for r in teacher['rows'] if r['forced_option_id']=='sustained_e070_r255');assert s['outcome']['task_outcome']=='failure' and t['outcome']['task_outcome']=='pass'
si=replay.read_bound(s['sensor']);ti=replay.read_bound(t['sensor']);assert si['timed_policy_sha256']==sm['policy']['sha256'];identity=replay.group_identity(sm['registry'],sm['scene_definition'],93202)
sdigest=replay.history_id(identity,replay.raw_payload(s['trajectory']),si,tick);tdigest=replay.history_id(identity,replay.raw_payload(t['trajectory']),ti,tick);target=next(x for x in group['targets'] if x['phase_tick']==tick);assert sdigest==tdigest==target['recorded_history_sha256']
sp=next(p for p in si['observations'] if p['tick']==tick);tp=next(p for p in ti['observations'] if p['tick']==tick);assert sp['features']==tp['features']==target['features'];assert sp['legal_mask']==tp['legal_mask']==target['legal_mask'];ids=group['option_ids'];chosen=sp['selected_option_id'];assert chosen=='short_e070_r265';assert target['complete_legal_action_table'];assert sp['legal_mask'][ids.index('sustained_e070_r255')]
passing_actions=[ids[i] for i,p in enumerate(target['pass_labels']) if p and target['legal_mask'][i]];assert passing_actions==['sustained_e070_r255']
report=dict(schema='motion2scene_matched_final_choice_readout_v1',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),run_id=c['run_id'],budget=7,scene_id=group['scene_id'],completion=cp,preupdate=pre_ref,generating_model=sm['policy'],new_model=c['model'],student_collection=sr_ref,teacher_collection=group['collection'],registry=sm['registry'],physics_seed=93202,student_raw_trajectory=s['trajectory'],passing_teacher_raw_trajectory=t['trajectory'],student_sensor=s['sensor'],passing_teacher_sensor=t['sensor'],phase_tick=tick,preaction_capture_elapsed_s=sp['capture_elapsed_s'],recorded_history_sha256=sdigest,student_and_passing_teacher_recorded_histories_match=True,stored_complete_teacher_prefix_matches=True,causal_features_match=True,legal_mask_matches=True,selected_option_id=chosen,passing_immediate_actions=passing_actions,teacher_action=target['teacher_action'],student_outcome=s['outcome'],passing_teacher_outcome=t['outcome'],passing_teacher_passage_time_s=t['costs']['passage_time_s'],original_teacher_prefix_preserved=True,weighting=reg['weighting'],learner_l2=reg['l2'],new_physical_executions=0,new_fits=0,verification_scope='Recomputed one final pre-action history digest from hash-checked raw trajectories and interfaces, compared with the completed teacher target. Uses bound original outcome scoring; no second full-episode raw scoring or refit.',interpretation='At the same recorded neutral prefix at tick70, the generating M6 student selects failing late short while late sustained is legal, has a complete passing teacher continuation, and passes its actual forced execution. This is an acquired-scene final-choice failure relative to measured finite-bank capability. It does not prove perceptual realizability across scenes, isolate WAIT information benefit, or evaluate the new M7 model. Earlier WAIT choices must not be assigned this whole-continuation failure as separate immediate errors. The digest binds recorded history, not unrecorded simulator hidden state.')
f=o/'seed93202_target_M7_final_choice_readout.json';assert not f.exists();f.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');print(json.dumps(dict(output=ref(f),recorded_prefix_match=True,selected=chosen,passing_immediate_actions=passing_actions,passing_time_s=report['passing_teacher_passage_time_s'],student_events=s['outcome']['physical_events'],new_physics=0,new_fits=0)))
PY

